version: "3.7"

services:
  wpdb: 
    image: lscr.io/linuxserver/mariadb:latest
    volumes:
      - /srv/wordpress-db:/config
    restart: always
    container_name: wpdb
    environment:
      PUID: 1000
      PGID: 1000
      TZ: "${DB_TIMEZONE}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - /srv/wordpress-data:/var/www/html
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    ports:
      - "${PORT_HTTP}:80"
      - "${PORT_HTTPS}:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"

  phpmyadmin:
    depends_on:
      - wpdb
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      #- PMA_HOST=wpdb
      #- PMA_VERBOSE=wp-database
      #- PMA_USER=wordpress
      #- PMA_PASSWORD=vFvp5345gfdFSDdaDp4%
      - HIDE_PHP_VERSION=true
    restart: always
    ports:
      - "${PORT_PHPMA}:80"
    volumes:
      - /sessions
